# Generated by Django 2.2 on 2019-09-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0003_auto_20190907_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='events',
        ),
        migrations.RemoveField(
            model_name='users',
            name='events',
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='users', to='eventFinderApp.Users'),
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', to='eventFinderApp.Category'),
        ),
    ]
